spring:
  application.name: lab_2_spring_boot_security
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: user
      password: password
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: google-client
          github:
            provider: github
            clientId: ${GITHUB_ID}
            clientSecret: ${GITHUB_SECRET}
            scope: user:email, read:user
            client-name: github-client
        provider:
          google.user-name-attribute: email
          github.user-name-attribute: login
