version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    command: >
      bash -c "
      docker-entrypoint.sh postgres &&
      psql -U $POSTGRES_USER -d postgres -c 'CREATE DATABASE order;' &&
      psql -U $POSTGRES_USER -d postgres -c 'CREATE DATABASE product;' "
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s
    networks:
      - lab-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: lab-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command:
      [
        "start-dev",
        "--db=postgres",
        "--db-url-host=postgres",
        "--db-username=postgres",
        "--db-password=password",
        "--db-url-database=keycloak"
      ]
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
    external: true