spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes[0]:
        id: product-service
        uri: lb://product-service
        predicates[0]: Path=/api/products/**
      routes[1]:
        id: order-service
        uri: lb://order-service
        predicates[0]: Path=/api/orders/**
#      default-filters: TokenRelay

    # Below property tells API Gateway to work in a load balanced mode
    loadbalancer:
      enabled: true

  # Configuration for connecting to keycloak server
  security:
    oauth2:
      resourceserver:
        jwt:
          # You can specify either jwk-set-uri or issuer-uri
          jwk-set-uri: ${JWK_SET_URI}
          issuer-uri: ${ISSUER_URI}
      client:
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI}
        registration:
          ${CLIENT_ID}:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            provider: keycloak
            authorization-grant-type: authorization_code
            scope: openid

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_URI}
  instance:
    hostname: ${GATEWAY_HOST_NAME}
    instance-id: ${spring.application.name}:${random.uuid}
